
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int coma = 5;
  public static final int estudiante = 9;
  public static final int mcurso = 13;
  public static final int pareni = 3;
  public static final int pcoma = 6;
  public static final int EOF = 0;
  public static final int parend = 4;
  public static final int bestudiante = 10;
  public static final int ID = 7;
  public static final int error = 1;
  public static final int mestudiante = 12;
  public static final int curso = 8;
  public static final int eestudiante = 11;
  public static final int nombre = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "nombre",
  "pareni",
  "parend",
  "coma",
  "pcoma",
  "ID",
  "curso",
  "estudiante",
  "bestudiante",
  "eestudiante",
  "mestudiante",
  "mcurso"
  };
}

